name: 'Sintesi - Documentation AI'
description: 'Automated documentation system. Detects drift and auto-creates PRs with AI-generated fixes for README and Guides.'
author: 'doctypedev'
branding:
  icon: 'book'
  color: 'white'

inputs:
  openai_api_key:
    description: 'Your OpenAI API Key'
    required: true
  github_token:
    description: 'GitHub Token to create Pull Requests (standard GITHUB_TOKEN works)'
    required: true
  cohere_api_key:
    description: 'Your Cohere API Key'
    required: false
  version:
    description: 'Version of Sintesi to use'
    required: false
    default: 'latest'
  readme_output:
    description: 'Path for the output README file'
    required: false
    default: 'README.md'
  docs_output:
    description: 'Directory for the output documentation'
    required: false
    default: 'docs'
  targets:
    description: 'Documentation targets to generate (comma-separated). Options: readme, docs'
    required: false
    default: 'readme,docs'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Sintesi
      shell: bash
      run: |
        echo "📦 Installing Sintesi..."
        npm install -g @sintesi/sintesi@${{ inputs.version }}

    - name: Cache Sintesi RAG State
      uses: actions/cache@v4
      with:
        path: .sintesi
        key: sintesi-rag-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          sintesi-rag-${{ runner.os }}-

    - name: Run Sintesi Logic
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GH_TOKEN: ${{ inputs.github_token }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      run: |
        echo "🔍 Configuring Sintesi..."
        git config --global user.name "Sintesi Bot"
        git config --global user.email "bot@sintesicli.dev"

        TARGETS="${{ inputs.targets }}"

        # 1. Checks Phase
        if [[ "$TARGETS" == *"readme"* ]]; then
          echo "🔍 Running Sintesi Check (README)..."
          sintesi check --readme --output ${{ inputs.readme_output }} --no-strict --verbose
        fi

        if [[ "$TARGETS" == *"docs"* ]]; then
          echo "🔍 Running Sintesi Check (Documentation)..."
          sintesi check --doc --output-dir ${{ inputs.docs_output }} --no-strict --verbose
        fi

        # 2. Generation Phase
        if [[ "$TARGETS" == *"readme"* ]]; then
          echo "📝 Processing README..."
          sintesi readme --output ${{ inputs.readme_output }} --verbose
        else
          echo "⏭️ Skipping README generation..."
        fi
        
        if [[ "$TARGETS" == *"docs"* ]]; then
          echo "📚 Processing Documentation Site..."
          sintesi documentation --output-dir ${{ inputs.docs_output }} --verbose
        else
          echo "⏭️ Skipping Documentation generation..."
        fi

        if [ -z "$(git status --porcelain)" ]; then 
          echo "✅ No documentation changes required."
          exit 0
        fi

        # 3. Formatting Phase
        if [ -f "package.json" ]; then
          echo "🎨 Checking for formatting tools..."
        
          PKG_MANAGER="npm"
          INSTALL_CMD="npm ci --silent"
          RUN_CMD="npm run"
          EXEC_CMD="npx"

          if [ -f "pnpm-lock.yaml" ]; then
            PKG_MANAGER="pnpm"
            INSTALL_CMD="pnpm install --frozen-lockfile --silent"
            RUN_CMD="pnpm run"
            EXEC_CMD="pnpm exec"
          elif [ -f "yarn.lock" ]; then
            PKG_MANAGER="yarn"
            INSTALL_CMD="yarn install --frozen-lockfile --silent"
            RUN_CMD="yarn run"
            EXEC_CMD="yarn run" # yarn run <bin> funziona come npx
          fi

          echo "📦 Installing dependencies using $PKG_MANAGER..."
          $INSTALL_CMD || true 

          # Prettier
          if grep -q '"prettier"' package.json; then
            echo "✨ Prettier found. Formatting..."
            if grep -q '"format"' package.json; then
              $RUN_CMD format || true
            else
              $EXEC_CMD prettier --write "${{ inputs.docs_output }}" "${{ inputs.readme_output }}" || true
            fi
          fi

          # ESLint
          if grep -q '"eslint"' package.json; then
             echo "🛡️ ESLint found. Fixing..."
             if grep -q '"lint:fix"' package.json; then
                $RUN_CMD lint:fix || true
             else
                # Fallback generico
                $EXEC_CMD eslint --fix "${{ inputs.docs_output }}" || true
             fi
          fi
        fi
        
        if [ -z "$(git status --porcelain)" ]; then 
          echo "✅ No documentation or formatting changes required."
          exit 0
        fi

        echo "⚠️ Drift, Updates or Formatting changes detected! Creating Pull Request..."

        BRANCH_NAME="sintesi/docs-update-${{ github.run_id }}"
        git checkout -b "$BRANCH_NAME"

        git add .
        git commit -m "docs: auto-update documentation via Sintesi [skip ci]"
        git push origin "$BRANCH_NAME" --force

        echo "🚀 Creating Pull Request..."
        gh pr create \
          --title "🤖 Sintesi: Automated Documentation Update" \
          --body "Sintesi detected a drift between your code and documentation. This PR aligns the drift detected using GenAI." \
          --base "main" \
          --head "$BRANCH_NAME"

        echo "✅ Pull Request created successfully."
