name: 'Sintesi - Documentation AI'
description: 'Automated documentation system. Detects drift and auto-creates PRs with AI-generated fixes for README and Guides.'
author: 'doctypedev'
branding:
  icon: 'book'
  color: 'white'

inputs:
  openai_api_key:
    description: 'Your OpenAI API Key'
    required: true
  github_token:
    description: 'GitHub Token to create Pull Requests (standard GITHUB_TOKEN works)'
    required: true
  version:
    description: 'Version of Sintesi to use'
    required: false
    default: 'latest'
  readme_output:
    description: 'Path for the output README file'
    required: false
    default: 'README.md'
  docs_output:
    description: 'Directory for the output documentation'
    required: false
    default: 'docs'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Sintesi
      shell: bash
      run: |
        echo "📦 Installing Sintesi..."
        npm install -g @sintesi/sintesi@${{ inputs.version }}

    - name: Run Sintesi Logic
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        git config --global user.name "Sintesi Bot"
        git config --global user.email "bot@sintesi.ai"

        echo "🔍 Running Sintesi Smart Check..."
        sintesi check --no-strict --verbose

        echo "📝 Processing README..."
        sintesi readme --output ${{ inputs.readme_output }} --verbose
        
        echo "📚 Processing Documentation Site..."
        sintesi documentation --output-dir ${{ inputs.docs_output }} --verbose

        if [ -z "$(git status --porcelain)" ]; then 
          echo "✅ No documentation changes required."
          exit 0
        fi

        echo "⚠️ Drift or Updates detected! Creating Pull Request..."

        BRANCH_NAME="sintesi/docs-update-${{ github.run_id }}"
        git checkout -b "$BRANCH_NAME"

        git add .
        git commit -m "docs: auto-update documentation via Sintesi [skip ci]"
        git push origin "$BRANCH_NAME"

        echo "🚀 Creating Pull Request..."
        gh pr create \
          --title "🤖 Sintesi: Automated Documentation Update" \
          --body "Sintesi detected a drift between your code and documentation. This PR aligns the README and Public Guides using GenAI." \
          --base "main" \
          --head "$BRANCH_NAME" \
          --label "documentation,automated"

        echo "✅ Pull Request created successfully."
